### ISSUE TITLE
BEP33

### ISSUE THREAD

**Issue by XJIOP** [mafintosh/k-rpc#16]
k-rpc has support BEP33?
http://www.bittorrent.org/beps/bep_0033.html

tried request get_peers with scrape 1, in reply received values only one ip array, should be 2 arrays.

**Comment by XJIOP** [comment]
all right, I'm getting two arrays BFpe and BFsd

**Comment by XJIOP** [comment]
ok  I'm getting two arrays BFpe and BFsd, but any way to decode it?

**Comment by feross** [comment]
We don't support BEP33 as far as I'm aware. You must be getting responses from other DHT implementations on the network. It's up to you to figure out how to decode them.
